name: Deploy to GitHub Pages

permissions:
  contents: write        # 소스 코드(gh-pages 브랜치 포함) push 권한
  pages: write           # GitHub Pages API 권한
  id-token: write        # peaceiris/actions-gh-pages가 OIDC 토큰을 쓸 때 필요
  
# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스코드 체크아웃
      - uses: actions/checkout@v3

      # 2) Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4) Vite 빌드 (dist 폴더 생성)
      - name: Build
        run: npm run build

      # 5) gh-pages 브랜치로 배포
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
